<?php

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tengstrom_views_form_views_exposed_form_alter(array &$form, FormStateInterface $formState, string $formId): void {
  /** @var \Drupal\tengstrom_views\HookHandlers\ViewsExposedFormAlterHandler $service */
  $service = \Drupal::service('tengstrom_views.hook_handlers.views_exposed_form_alter');

  $service->alter($form, $formState, $formId);
}

/**
 * Implements hook_views_plugins_filter_alter().
 */
function tengstrom_views_views_plugins_filter_alter(array &$plugins): void {
  /** @var \Drupal\tengstrom_views\HookHandlers\ViewsFilterPluginsAlterHandler $service */
  $service = \Drupal::service('tengstrom_views.hook_handlers.views_filter_plugins_alter');

  $service->alter($plugins);
}

/**
 * Implements hook_preprocess_views_exposed_form().
 */
function tengstrom_views_preprocess_views_exposed_form(array &$variables) {
  /** @var \Drupal\tengstrom_views\HookHandlers\PreprocessHandlers\PreprocessViewsExposedFormHandler $service */
  $service = \Drupal::service('tengstrom_views.hook_handlers.preprocess_views_exposed_form');

  $service->preprocess($variables);
}
